//
// Created by camps on 4/7/2023.
//

#ifndef MORTARCOMPUTER_WEATHERFUNCTIONS_H
#define MORTARCOMPUTER_WEATHERFUNCTIONS_H

// USE WEATHER FORMULAS TO MAKE A COOL THING

#endif //MORTARCOMPUTER_WEATHERFUNCTIONS_H
